# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160918000915 on 2016-10-13 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popular_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='exp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
